### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Point'

### ISSUE THREAD

**Issue by dimaliv** [ivandm/django-geopositionmap#2]
Django 1.8.1

$ python manage.py makemigrations

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "c:\projects\esite\venv\lib\site-packages\django\core\management__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "c:\projects\esite\venv\lib\site-packages\django\core\management__init__.py", line 312, in execute
    django.setup()
  File "c:\projects\esite\venv\lib\site-packages\django__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "c:\projects\esite\venv\lib\site-packages\django\apps\registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "c:\projects\esite\venv\lib\site-packages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Python27\Lib\importlib__init__.py", line 37, in import_module
    **import**(name)
  File "C:\projects\esite\src\efirms\models.py", line 73, in <module>
    class Office(models.Model):
  File "C:\projects\esite\src\efirms\models.py", line 81, in Office
    position = LatLngField()
  File "c:\projects\esite\venv\lib\site-packages\geopositionmap\geoFields.py", line 33, in **init**
    p = LatLng()
  File "c:\projects\esite\venv\lib\site-packages\geopositionmap__init__.py", line 52, in **init**
    self._geosPoint = geos.Point((self._lng, self._lat))
AttributeError: 'module' object has no attribute 'Point'

I can`t run my project with "position = LatLngField()"' im model.

**Comment by dimaliv** [comment]
Oh, its ok ) 
These two lines are fixed it:

> from geopositionmap.geoManager import geoManager
> objects = geoManager()

Thanks )
